author: xcode.swift
module: xclint
module_version: 0.0.1
github_url: https://github.com/xcodeswift/xclint
copyright: 'Copyright © 2017 xcode.swift. All rights reserved.'
readme: ABOUT.md
documentation: guides/*.md
