author: Caramba
author_url: https://twitter.com/carambalabsEng
module: xcodeprojlint
module_version: 0.0.1
github_url: https://github.com/carambalabs/xcodeprojlint
copyright: 'Copyright © 2017 Caramba. All rights reserved.'
documentation: guides/*.md
custom_categories:
  - name: Commands
    children:
      - RulesCommand
      - AutoCorrectCommand
      - LintCommand
  - name: Protocols
    children:
      - XcodeprojLinting
