author: swift-xcode
module: xclint
module_version: 0.0.1
github_url: https://github.com/swift-xcode/xclint
copyright: 'Copyright © 2017 swift-xcode. All rights reserved.'
readme: ABOUT.md
documentation: guides/*.md
