author: Caramba
author_url: https://twitter.com/carambalabsEng
module: xcodeprojlint
sourcekitten_sourcefile: docs.json 
module_version: 0.0.1
github_url: https://github.com/carambalabs/xcodeprojlint
copyright: 'Copyright © 2017 Caramba. All rights reserved.'
readme: ABOUT.md
documentation: guides/*.md